name: CI testing flow for litetorch package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t litetorch-ci .

      - name: Run Tests
        run: docker run --rm litetorch-ci poetry run pytest
